### ISSUE TITLE
Remove Locked items

### ISSUE THREAD

**Issue by andmcadams** [weirdgloop/osrs-dps-calc#77] opened 2024-01-13 19:37 UTC
### What feature would you like to see?

Locked items are the same as the Normal variant as far as stats go, so it's not really useful to have both IMO. If you get rid of the locked ones then the Normal variant can just not have that at the end, which is nice
Ex: https://oldschool.runescape.wiki/w/Fire_cape#Locked
leads to
![image](https://github.com/weirdgloop/osrs-dps-calc/assets/5871961/f22c7a13-1f6c-4ef2-8616-12d99f6e4743)

**Comment by jayktaylor** [comment] 2024-01-13 19:39
Dupe of #39

**Closed by jayktaylor** 2024-01-13 19:39 UTC
Labels: feature request, triage
