### ISSUE TITLE
filter item list

### ISSUE THREAD

**Issue by crab-pancake** [weirdgloop/osrs-dps-calc#40] opened 2024-01-11 00:36 UTC
### What feature would you like to see?

remove all cosmetic gear with no stats (should be simple to automate? esp. if limiting to non-weapons)

remove variants of the same item that have the same stats (probably done manually)

something similar could be done with monsters but i cant think of anything that needs it off the top of my head

**Comment by jayktaylor** [comment] 2024-01-11 00:42
Dupe of #39, who seems to have *just* beat you to it 😀

**Closed by jayktaylor** 2024-01-11 00:42 UTC
Labels: duplicate, feature request
