### ISSUE TITLE
Add potentially upcoming items (Firelight, etc.)

### ISSUE THREAD

**Issue by SilensAngelusNex** [weirdgloop/osrs-dps-calc#336] opened 2024-05-25 07:17 UTC
### What feature would you like to see?

Would you be willing, in general, to support proposed items or should the supported equipment list be limited to items actually in the game?

I'd like to be able to run calcs for the [proposed WGS weapons](https://secure.runescape.com/m=news/a=13/while-guthix-sleeps---rewards?oldschool=1), especially Firelight and the Scorching Bow. I'd be happy to send a pull request.

**Comment by jayktaylor** [comment] 2024-08-12 18:27
Gonna close this as a duplicate of #209 for now (where we plan to allow people to edit equipment stats manually/input custom equipment). And of course, the WGS stuff has now been released :P

**Closed by jayktaylor** 2024-08-12 18:27 UTC
Labels: data, ui, feature request
